### ISSUE TITLE
Importance of Simulating Survival Times?

### ISSUE THREAD

**Issue by swaheera** [sambrilleman/simsurv#16]
Hello Dr. Brilleman,

I was reading about your R package on simulating survival times (https://cran.r-project.org/web/packages/simsurv/index.html)

I have heard that simulation can be used to evaluate properties relating to the "robustness" and "misspecification" of a statistical model. 

- For example, suppose I fit a Longitudinal Regression Model to my data and pick a specific covariance structure - I can then simulate data from a probability distribution having a different covariance structure, and see how well my model performs as I move away from the conditions that my model was created in. 

- Another example - suppose I fit a parametric Survival Model in which I assume that my Survival Times have an Exponential Distribution. I might then simulate data for new patients in which Survival Times follow a Gamma Distribution or a Weibull Distribution, and see how accurately (i.e. robust) my model performs under this deliberate misspecification.

I was then reading your reference (https://www.jstatsoft.org/article/view/v097i03) in which it states : "_When conducting simulation studies to evaluate the performance of new and existing statistical methods for analyzing survival data, one is required to simulate event times under a known data generating model. Similarly, one may need to simulate event times for the purpose of power calculations when designing new studies._"

Given this information, I just wanted to clarify the following point: 

- Are we ever required to simulate data from the same distribution as the model itself? Or does this by definition provide no new information to us?
-  As an example, suppose I decide to fit a specific parametric Survival Model (e.g. AFT - Accelerated Failure Time Model) to some data 
- I  collected. I read that there a methods that use the "Inverse Probability Transform Method" that can then simulate Survival Times from this same "data-dependent probability distribution function" corresponding to my model. Such methods also exist in the semi-parametric case, where it becomes significantly more difficult to simulate Survival Times from a probability distribution that has not been explicitly defined.

This being said, I am trying to understand why exactly this is important and useful:

- If I simulate Survival Times from the same distribution corresponding to the model I just fit - won't my model be able to handle this data well by definition (i.e. "home field advantage")?
- **Why is it important to simulate data from the same distribution as the model** - would it not almost always be more useful to simulate Survival Times from a different distribution and see how well my model adapts (i.e. how close the predictions are) to this new data?

Your Help Is Greatly Appreciated,
Thanks,

**Comment by sambrilleman** [comment]
Hi @swaheera - some answers inline below, hope they help!

> Are we ever required to simulate data from the same distribution as the model itself? Or does this by definition provide no new information to us?

You might want to do this to check that your analysis model implementation can recover the "true" parameters of the data generating model that you used to simulate the data.

> As an example, suppose I decide to fit a specific parametric Survival Model (e.g. AFT - Accelerated Failure Time Model) to some data I collected. I read that there a methods that use the "Inverse Probability Transform Method" that can then simulate Survival Times from this same "data-dependent probability distribution function" corresponding to my model. Such methods also exist in the semi-parametric case, where it becomes significantly more difficult to simulate Survival Times from a probability distribution that has not been explicitly defined.

Sorry I'm not familiar with the "Inverse Probability Transform Method"!

> If I simulate Survival Times from the same distribution corresponding to the model I just fit - won't my model be able to handle this data well by definition (i.e. "home field advantage")?

As mentioned above - yes - and this is why you would do it - you want to check that the "home field advantage" is such that your analysis model can recover the true parameters, and therefore your implementation of the analysis model is correct.

> Why is it important to simulate data from the same distribution as the model - would it not almost always be more useful to simulate Survival Times from a different distribution and see how well my model adapts (i.e. how close the predictions are) to this new data?

As above. But yes, using a data generating model that is different from your analysis model is also a useful endeavour - it allows you to assess the impacts of model misspecification, e.g. properties like bias etc. So, it really depends of the goals of your simulation study...

**Comment by swaheera** [comment]
@sambrilleman  : thank you so much for your kind answers!

**Comment by swaheera** [comment]
One other question I wanted to ask - in general, it is not possible to simulate data from a Cox-PH model without making some assumption about the Baseline Hazard? 

E.g. if I fit a Cox-PH model to some data, I am NOT required to specify a distribution for the Baseline Hazard Function. However, I want to simulate data from this same model, then I NEED to specify a distribution for the Baseline Hazard Function. **Is this correct?**

Thank you so much!

**Comment by sambrilleman** [comment]
Yeah that's correct.

No worries, happy to have helped. 🙂
