### ISSUE TITLE
Controlling the censored proportion

### ISSUE THREAD

**Issue by ielbadisy** [sambrilleman/simsurv#18]
Hi Sam,

Thank you very much for this great package. 

I wonder if you have any suggestion how I could control the percentage of censoring without changing either the `maxt` or the values of baseline ?

Many thanks.

**Comment by sambrilleman** [comment]
Hi @ielbadisy. No, unfortunately the censoring mechanism in simsurv is pretty simplistic. As far as I can remember, it just has non-informative censoring based on a maximum time `maxt`. If you have a specific hazard function and a desired censoring proportion, then I guess you could write a loop or something to iterate over a range of possible `maxt` until you hit the `maxt` that gets you the censoring proportion you desire... 🤔

**Comment by ielbadisy** [comment]
Hi @sambrilleman,
Thanks for responding. I see the proposed solution. I wil try to work on a solution and will give you feedback later. Although I believe that with this option, we lose control over the desired `maxt`.
